// Background combinations
export const backgrounds = [
  {
    id: 1,
    mood: `SpiritualPsychic`,
    mobile: "/moodBackgrounds/sm/SpiritualPsychic.png",
    desktop: "/moodBackgrounds/lg/SpiritualPsychic.png",
  },
  {
    id: 2,
    mood: `CalmRecharged`,
    mobile: "/moodBackgrounds/sm/CalmRecharged.png",
    desktop: "/moodBackgrounds/lg/CalmRecharged.png",
  },
  {
    id: 3,
    mood: `AngryJealous`,
    mobile: "/moodBackgrounds/sm/AngryJealous.png",
    desktop: "/moodBackgrounds/lg/AngryJealous.png",
  },
  {
    id: 4,
    mood: `AnxiousFearful`,
    mobile: "/moodBackgrounds/sm/AnxiousFearful.png",
    desktop: "/moodBackgrounds/lg/AnxiousFearful.png",
  },
  {
    id: 5,
    mood: `AbundantManifesting`,
    mobile: "/moodBackgrounds/sm/AbundantManifesting.png",
    desktop: "/moodBackgrounds/lg/AbundantManifesting.png",
  },
  {
    id: 6,
    mood: `AdorableSassy`,
    mobile: "/moodBackgrounds/sm/AdorableSassy.png",
    desktop: "/moodBackgrounds/lg/AdorableSassy.png",
  },
  {
    id: 7,
    mood: `BrokenTrustSuspicious`,
    mobile: "/moodBackgrounds/sm/BrokenTrustSuspicious.png",
    desktop: "/moodBackgrounds/lg/BrokenTrustSuspicious.png",
  },
  {
    id: 8,
    mood: `DisorganizedConfused`,
    mobile: "/moodBackgrounds/sm/DisorganizedConfused.png",
    desktop: "/moodBackgrounds/lg/DisorganizedConfused.png",
  },
  {
    id: 9,
    mood: `AdventurousFearless`,
    mobile: "/moodBackgrounds/sm/AdventurousFearless.png",
    desktop: "/moodBackgrounds/lg/AdventurousFearless.png",
  },
  {
    id: 10,
    mood: `EmbarrassedAshamed`,
    mobile: "/moodBackgrounds/sm/EmbarrassedAshamed.png",
    desktop: "/moodBackgrounds/lg/EmbarrassedAshamed.png",
  },
  {
    id: 11,
    mood: `InsecureUnworthy`,
    mobile: "/moodBackgrounds/sm/InsecureUnworthy.png",
    desktop: "/moodBackgrounds/lg/InsecureUnworthy.png",
  },
  {
    id: 12,
    mood: `CharmingExtroverted`,
    mobile: "/moodBackgrounds/sm/CharmingExtroverted.png",
    desktop: "/moodBackgrounds/lg/CharmingExtroverted.png",
  },
  {
    id: 13,
    mood: `EmotionalThoughtful`,
    mobile: "/moodBackgrounds/sm/EmotionalThoughtful.png",
    desktop: "/moodBackgrounds/lg/EmotionalThoughtful.png",
  },
  {
    id: 14,
    mood: `SadHurt`,
    mobile: "/moodBackgrounds/sm/SadHurt.png",
    desktop: "/moodBackgrounds/lg/SadHurt.png",
  },
  {
    id: 15,
    mood: `SelfishJudgemental`,
    mobile: "/moodBackgrounds/sm/SelfishJudgemental.png",
    desktop: "/moodBackgrounds/lg/SelfishJudgemental.png",
  },
  {
    id: 16,
    mood: `FlirtatiousAroused`,
    mobile: "/moodBackgrounds/sm/FlirtatiousAroused.png",
    desktop: "/moodBackgrounds/lg/FlirtatiousAroused.png",
  },
  {
    id: 17,
    mood: `HappyExcited`,
    mobile: "/moodBackgrounds/sm/HappyExcited.png",
    desktop: "/moodBackgrounds/lg/HappyExcited.png",
  },
  {
    id: 18,
    mood: `StressedBurntOut`,
    mobile: "/moodBackgrounds/sm/StressedBurntOut.png",
    desktop: "/moodBackgrounds/lg/StressedBurntOut.png",
  },
  {
    id: 19,
    mood: `UnproductiveLazy`,
    mobile: "/moodBackgrounds/sm/UnproductiveLazy.png",
    desktop: "/moodBackgrounds/lg/UnproductiveLazy.png",
  },
  {
    id: 20,
    mood: `HonestCooperative`,
    mobile: "/moodBackgrounds/sm/HonestCooperative.png",
    desktop: "/moodBackgrounds/lg/HonestCooperative.png",
  },
  {
    id: 21,
    mood: `IntelligentTalented`,
    mobile: "/moodBackgrounds/sm/IntelligentTalented.png",
    desktop: "/moodBackgrounds/lg/IntelligentTalented.png",
  },
  {
    id: 22,
    mood: `UnstableLosingit`,
    mobile: "/moodBackgrounds/sm/UnstableLosingit.png",
    desktop: "/moodBackgrounds/lg/UnstableLosingit.png",
  },
  {
    id: 23,
    mood: `LovingSupportive`,
    mobile: "/moodBackgrounds/sm/LovingSupportive.png",
    desktop: "/moodBackgrounds/lg/LovingSupportive.png",
  },
  {
    id: 24,
    mood: `MagneticFascinated`,
    mobile: "/moodBackgrounds/sm/MagneticFascinated.png",
    desktop: "/moodBackgrounds/lg/MagneticFascinated.png",
  },
  {
    id: 25,
    mood: `WorkFocusedCreative`,
    mobile: "/moodBackgrounds/sm/WorkFocusedCreative.png",
    desktop: "/moodBackgrounds/lg/WorkFocusedCreative.png",
  },
  {
    id: 26,
    mood: `IndifferentNeutral`,
    mobile: "/moodBackgrounds/sm/IndifferentNeutral.png",
    desktop: "/moodBackgrounds/lg/IndifferentNeutral.png",
  },
  {
    id: 27,
    mood: `WorthyConfident`,
    mobile: "/moodBackgrounds/sm/WorthyConfident.png",
    desktop: "/moodBackgrounds/lg/WorthyConfident.png",
  },
]